name = "BeamEstimation"
uuid = "7daf6946-dcf1-484b-aa60-b20f34902b49"
authors = ["ferreol Soulez <ferreol.soulez@univ-lyon1.fr>"]
version = "0.1.0"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"
OIFITS = "53eb397e-dec1-5dcf-8dc9-2db916067267"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAngles = "6fb2a4bd-7999-5318-a3b2-8ad61056cd98"
